# fly.toml app configuration file generated for forum-lingering-leaf-9073 on 2025-04-23T16:05:59-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'forum-lingering-leaf-9073'
primary_region = 'iad'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 5050
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
MYSQL_HOST = "mysql-bold-flower-4970.internal"
MYSQL_PORT = "3306"
MYSQL_USER = "non_root_user"
MYSQL_DATABASE = "some_db"
