# fly.toml app configuration file generated for laserstream on 2025-05-01T09:37:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laserstream'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-1x'
