# fly.toml app configuration file generated for laserstream-groupy on 2025-05-14T00:29:28-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laserstream-groupy'
primary_region = 'iad'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 4040
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'performance-1x'
